app = "caffeinated-divas"
primary_region = "lax" # or your preferred region

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  DJANGO_SETTINGS_MODULE = "bingo.settings"
  DEBUG = "false"